### ISSUE TITLE
How to get currently selected account?

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#10]
Hi,

I'm trying to interact with our smart contract with my currently selected account.
I succeded getting an instance of the contract for read only queries with 
`const contract = new ethers.Contract(contractAddress, abi, provider);`
where provider is your evm-provider.

I see in the ethers doc that for state changing operations I need a signer (`const contract = new ethers.Contract(contractAddress, abi, signer);`).
I suppose the signer is the currently connected account in the polkadot{.js} extension.
I have the Chrome extension installed with a new account, and allowed it to work with every chain.
![aaa](https://user-images.githubusercontent.com/17194393/134412805-6373d734-0419-4928-b099-6cb5f215a36b.PNG)

I read on the "Migration: From Web3.js" at docs.ethers.io that I should be able to get a signer with
`const signer = provider.getSigner();`
but I tried it with your evm-provider and it didn't work.
How can I obtain it?

Thanks

**Comment by 4skinSkywalker** [comment]
I just connected polkadot{.js} Chrome extension with the NPM package @polkadot/extension-dapp, using the following code:
```
await web3Enable('my cool dapp');
const allAccounts = await web3Accounts();
```
and I was able to get a dialog and after accepting the request I got my hands on my address from inside the code.

Now I see your Signer has the following constructor sign `constructor(provider: Provider, address: string, signingKey: SigningKey);`.
What I need to pass as SigningKey?

**Comment by jbargu** [comment]
[`ui-examples`](https://github.com/reef-defi/ui-examples) repo has a single file example on how to use the extension for interacting with EVM:"
- `accountSigner` is set here: https://github.com/reef-defi/ui-examples/blob/master/packages/example-react/src/index.tsx#L189
- and then used for the signing here: https://github.com/reef-defi/ui-examples/blob/master/packages/example-react/src/index.tsx#L112

`SigningKey` can either be the extension signer like above (it will pop up the dialog to sign the transaction) or a plain static signing key for non-interactive use (for example background job or CLI application) as seen [here](https://github.com/reef-defi/reefswap/blob/master/src/setup.ts#L32).

**Comment by 4skinSkywalker** [comment]
Thank you.
