### ISSUE TITLE
Chain ID is always 13939?

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#11]
It seems irrelevant that I use "wss://rpc-testnet.reefscan.com/ws" or "wss://rpc.reefscan.com/ws" to connect, I'll always get 13939 as the chain ID.
Is this intended?
In my old code I use this value to initialize different contracts, icons, links to scanners, etc...
How do I know I'm on the Reef Mainnet (or testnet) if I've only the provider object?
I've noticed "_runtimeChain" of type Text under "api" of the provider, can I reliably use this?
Thanks

**Comment by jbargu** [comment]
Yes, this is an arbitrary number and it is hardcoded in the provider. It was meant to distinguish the chain IDs on the [EVM list](https://chainlist.org/) but it is not actually implemented in the `reef-node`. You can currently use `await provider.api.rpc.system.chain()` that will return "Reef Mainnet"/"Reef Testnet" as per [chain spec](https://github.com/reef-defi/reef-chain/blob/master/node/src/chain_spec.rs#L248).
