### ISSUE TITLE
Unmet dependencies, should I worry?

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#12]
Should I worry of all the warnings that pop up after launching yarn?
I know it's just a warning but 90% of them come from @reef-defi/evm-provider, and I've installed so many things that don't output any warning so I'm worrying about the reliability of the code with all these.

![image](https://user-images.githubusercontent.com/17194393/135748759-4e030b3f-f22a-4367-8f2a-3d98eaf362e4.png)

**Comment by jbargu** [comment]
I haven't encountered any issues so far. However we are trying to improve it, if you see any issues please report it.
