### ISSUE TITLE
npm install @reef-defi/evm-provider is followed by ENOENT error

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#5]
I'm getting the following error when launching `npm install @reef-defi/evm-provider` from my command line.
Is this anything that I should worry about when working with your libraries?

![image](https://user-images.githubusercontent.com/17194393/131975876-08631a55-e736-4954-8772-c8e2721da4e7.png)

**Comment by jbargu** [comment]
Use `yarn`, `npm` does not work.

**Comment by 4skinSkywalker** [comment]
> Use `yarn`, `npm` does not work.

I see it now, you've mentioned this at the very bottom of the docs, could you please move it to the top and with the entire dependency installation commands?
