### ISSUE TITLE
require("@reef-defi/api") leads to "Cannot find module '@reef-defi/api-derive'"

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#6]
I'm getting the error `Cannot find module '@reef-defi/api-derive'` when importing with `require("@reef-defi/api")` library.

![image](https://user-images.githubusercontent.com/17194393/131980530-d41be339-a4fa-4fbc-8398-b153cf2fd58d.png)

Installing '.../api-derive' leads to `Cannot find module '@reef-defi/types'`.
Installing '.../types' leads to `Cannot find module '@reef-defi/type-definitions`.

And installing that solve the problem. Please be more specific in the getting started on what to `npm install` to make it work.

**Comment by jbargu** [comment]
`@reef-defi/evm-provider` should work without adding any of the aforementioned packages. This discussion belongs to https://github.com/reef-defi/reef.js repo.
