### ISSUE TITLE
Is it possible to get a Web3Provider from this EVM provider?

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/evm-provider.js#9]
I'm trying to integrate Reef Defi into our dapp (at www.ethbox.org/app/).

We used web3.js for pretty much everything.
In the docs I read "The Provider provides an API for interacting with nodes and is an instance of ethers.js AbstractProvider.".
There is a substantial difference between providers in web3.js and ethers.js, this for us means that we have to rewrite and test lot of code.

Is it possible to have a Web3-compatible provider instead of a ether.js-like? Or maybe have them both...

**Comment by jbargu** [comment]
Unfortunately no, the underlying EVM on Reef chain does not expose Web3 RPC.
